export const paths = {
  home: "/",
  about: "/about",
  services: "/services",
  carNumberLots: "/car-number-lots",
  carNumberLotDetails: (id = ":id") => `/car-number-lots/${id}`,
  news: "/news",
  newsDetails: (id = ":id") => `/news/${id}`,
  contacts: "/contacts",
  sellNumber: "/sellNumber",
  profile: "/profile",
  myLots: "/my-lots",
  auth: {
    login: "/login",
    register: "/register",
  },
  admin: {
    root: "/admin",
    carNumberLots: "/admin/lots",
    carNumberLotNew: "/admin/lots/new",
    carNumberLotEdit: (id = ":id") => `/admin/lots/${id}/edit`,
    carNumberLotDetails: (id = ":id") => `/admin/lots/${id}`,
    users: "/admin/users",
    posts: "/admin/posts",
    postNew: "/admin/posts/new",
    postEdit: (id = ":id") => `/admin/posts/${id}/edit`,
  },
  notFound: "*",
} as const;
